server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hilmiugurpolat/microservice-egitim-config-server.git"
          default-label: "master"
          skip-ssl-validation: true
          username: "hilmiugurpolat"
          password: ${GIT_KEY}