version: '3.8'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
        - "5432:5432"